apiVersion: v1
kind: Service
metadata:
    name: "saleorcoreservice-42a7"
    labels:
        app: "saleorcoreservice-42a7"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "saleorcoreservice-42a7"